project:
  type: website
  output-dir: docs

website:
  title: "tc2_Tadlock"
  navbar:
    left:
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: Portfolio
    

format:
  html:
    theme:  
      light: simplex
      dark: solar
    css: styles.css
    toc: true
  pdf:
    documentclass: report
  docx: default
  pptx:  
    reference-doc: view.pptx  
    incremental: true


